# Changes here will be overwritten by Copier
_commit: 0.16.4
_src_path: gh:pawamoy/copier-pdm
author_email: pierre.marijon-ext@aphp.fr
author_fullname: Pierre Marijon
author_username: natir
copyright_date: '2023'
copyright_holder: Pierre Marijon
copyright_holder_email: pierre.marijon-ext@aphp.fr
copyright_license: MIT License
insiders: false
project_description: A tool kit to manage many variant on desktop computer
project_name: variantplaner
python_package_command_line_name: variantplaner
python_package_distribution_name: variantplaner
python_package_import_name: variantplaner
repository_name: variantplaner
repository_namespace: natir
repository_provider: github.com

