site_name: "variantplaner"
site_description: "A tool kit to manage many variant on desktop computer"
site_url: "https://SeqOIA-IT.github.io/variantplaner"
repo_url: "https://github.com/SeqOIA-IT/variantplaner"
repo_name: "SeqOIA-IT/variantplaner"
site_dir: "site"
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, src/variantplaner]
copyright: Copyright &copy; 2025 GCS SeqOIA
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
- Home:
  - Overview: index.md
  - Usage: usage.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- API reference: reference/api.md
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md

theme:
  name: material
  custom_dir: docs/.overrides
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.instant.preview
  - navigation.path
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

extra_css:
  - css/material.css
  - css/mkdocstrings.css

extra_javascript:
- js/feedback.js

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - callouts
  - pymdownx.blocks.details
  - footnotes
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify:
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

plugins:
- autorefs
- search
- autorefs
- markdown-exec
- section-index
- coverage
- mkdocstrings:
    handlers:
      python:
        inventories:
        - https://docs.python.org/3/objects.inv
        - https://pola-rs.github.io/polars/py-polars/html/objects.inv
        - https://click.palletsprojects.com/en/8.1.x/objects.inv
        paths: [src]
        options:
          backlinks: tree
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          filters: ["!^_"]
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_source: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          filters: ["!^_"]
          summary: true
- git-revision-date-localized:
    enabled: !ENV [DEPLOY, false]
    enable_creation_date: true
    type: timeago
- minify:
    minify_html: !ENV [DEPLOY, false]
- group:
    enabled: !ENV [MATERIAL_INSIDERS, false]
    plugins:
    - typeset

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/SeqOIA-IT
  - icon: fontawesome/brands/gitter
    link: https://gitter.im/variantplaner/community
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/variantplaner/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
