---
site_name: VariantPlaner
site_description: A tool kit to manage many variant on desktop computer
site_url: https://natir.github.io/variantplaner
repo_url: https://github.com/natir/variantplaner
repo_name: natir/variantplaner
site_dir: site
watch:
  - mkdocs.yml
  - README.md
  - CONTRIBUTING.md
  - CHANGELOG.md
  - src/variantplaner
copyright: Copyright &copy; 2023 Pierre Marijon
edit_uri: edit/main/docs/

nav:
- Home:
  - Overview: index.md
  - Usages: usages.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
# defer to gen-files + literate-nav
- API reference:
  - variantplaner: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md
  - Benchmark: benchmark.md

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

extra_css:
  - css/material.css
  - css/mkdocstrings.css

markdown_extensions:
  - attr_list
  - admonition
  - callouts
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.blocks.details
  - footnotes
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify:
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

plugins:
- autorefs
- search
- markdown-exec
- gen-files:
    scripts:
    - scripts/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.txt
- coverage
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://pola-rs.github.io/polars/py-polars/html/objects.inv
        - https://click.palletsprojects.com/en/8.1.x/objects.inv
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          heading_level: 1
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          filters: ["!^_"]
- git-committers:
    enabled: !ENV [DEPLOY, false]
    repository: natir/variantplaner

- minify:
    minify_html: !ENV [DEPLOY, false]

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/natir
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/variantplaner/community
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/variantplaner/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
