site_name: "VariantPlaner"
site_description: "A tool kit to manage many variant on desktop computer"
site_url: "https://natir.github.io/variantplaner"
repo_url: "https://github.com/natir/variantplaner"
repo_name: "natir/variantplaner"
site_dir: "site"
watch: [README.md, CONTRIBUTING.md, CHANGELOG.md, src/variantplaner]

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- Usages: usages.md
# defer to gen-files + literate-nav
- Code Reference: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode


extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- admonition
- callouts
- pymdownx.emoji
- pymdownx.blocks.details
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: true

plugins:
- search
- markdown-exec
- gen-files:
    scripts:
    - scripts/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.txt
- coverage
- section-index
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://pola-rs.github.io/polars/py-polars/html/objects.inv
        - https://click.palletsprojects.com/en/8.1.x/objects.inv
        options:
          separate_signature: true
          merge_init_into_class: true
          docstring_options:
            ignore_init_summary: true
          filters: ["!^_"]

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/natir
