[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "variantplaner"
description = "A tool kit to manage many variant on desktop computer"
authors = [{name = "Pierre Marijon", email = "pierre.marijon-ext@aphp.fr"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
keywords = []
dynamic = ["version"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Documentation",
    "Topic :: Software Development",
    "Topic :: Utilities",
    "Typing :: Typed",
]
dependencies = [
    "polars[pandas,numpy,pyarrow,fsspec,xlsx2csv,deltalake,timezone]>=0.18",
    "click>=8.1.3",
    "typing-extensions>=4.5.0",
]

[project.urls]
Homepage = "https://natir.github.io/variantplaner"
Documentation = "https://natir.github.io/variantplaner"
Changelog = "https://natir.github.io/variantplaner/changelog"
Repository = "https://github.com/natir/variantplaner"
Issues = "https://github.com/natir/variantplaner/issues"

[project.scripts]
variantplaner = "variantplaner.cli:main"

[tool.pdm]
version = {source = "scm"}

[tool.pdm.build]
package-dir = "src"
editable-backend = "editables"

[tool.pdm.dev-dependencies]
duty = ["duty>=0.10"]
docs = [
    "altair>=5",
    "black>=23",
    "mkdocs>=1",
    "mkdocs-coverage>=0.2",
    "mkdocs-gen-files>=0.5",
    "mkdocs-literate-nav>=0.6",
    "mkdocs-material>=9",
    "mkdocs-section-index>=0.3",
    "mkdocstrings[python]>=0.22",
    "markdown-callouts>=0.3",
    "markdown-exec>=1.6",
    "toml>=0.10",
]
maintain = [
    "black>=23",
    "blacken-docs>=1",
    "git-changelog>=2",
]
quality = [
    "ruff>=0.0.276",
]
tests = [
    "pytest>=7",
    "pytest-cov>=4",
    "pytest-randomly>=3",
    "pytest-xdist>=3",
    "pytest-benchmark[histogram]>=4",
]
typing = [
    "mypy>=1",
    "types-markdown>=3",
    "types-toml>=0.10",
]
security = ["safety>=2"]
